### ISSUE TITLE
Well then owner tell me why its not working

### ISSUE THREAD

**Issue by totte1015** [raoulvdberge/rangedpumps#14]
https://imgur.com/a/HruGD

Its draining, its using up blocks, yet the internal tank stays empty, and nothing is coming out, I have "redstone signal disabled" so it should always extract, and the pipe is pressurized.

What am I doing wrong then?

**Comment by raoulvdberge** [comment]
It's draining at that location, but there is no lava there, so it goes to the next block. In 1.10.2, Ranged Pumps scans far-blocks first. In 1.12, it does near-first.

Again, read the project description on CurseForge.
