### ISSUE TITLE
[wanna donate]

### ISSUE THREAD

**Issue by SimulatorSia** [raoulvdberge/rangedpumps#16]
I love this mod!!!!!!!!
like I loved the block back in extra utilities and I love it now in this form too, if you guys got a donate button somewhere I'd be happy to show my affection to it.

**Comment by raoulvdberge** [comment]
Hi there!

Glad to hear that you enjoy the mod.

You can support me in 2 ways:

- Do a 1-time PayPal donation (right hand side on https://minecraft.curseforge.com/projects/ranged-pumps)
- Support me on Patreon (https://patreon.com/raoulvdberge)

Thank you!
