### ISSUE TITLE
Pump Scans Down To Bedrock

### ISSUE THREAD

**Issue by Boolyman** [raoulvdberge/rangedpumps#17]
I don't recall the pump taking so long to drain a pool in 1.10.2... I notice that it scans down to bedrock for every block now in 1.12.2... which, if your pool is only 4 blocks deep, means the pump isn't gathering any fluid 95% of the time.  Is there any way around this?

**Comment by raoulvdberge** [comment]
No

**Comment by raoulvdberge** [comment]
You can increase the block scan speed for non fluid blocks.
