### ISSUE TITLE
Pump does not respect range limit in Y axis

### ISSUE THREAD

**Issue by Syndaryl** [raoulvdberge/rangedpumps#19]
I've set the pump config to a range of 2, and placed it at Y level 64 over the ocean. It's scanning all the way down to bedrock and sucking up lava and exploding my equipment.

**Comment by raoulvdberge** [comment]
That is intended.

**Comment by Syndaryl** [comment]
Can the description on Curseforge be updated then? It doesn't mention this.

**Comment by raoulvdberge** [comment]
Done
