### ISSUE TITLE
Blocks Moved in Saved Game

### ISSUE THREAD

**Issue by cattrfly** [raoulvdberge/rangedpumps#2]
I'd just finished using the pump for the first time and turned it off when I did something stupid unrelated to the pump - I hit the elevator floor selection button on my RF Tools screen with a pickax in my hand, destroying the screen. x.x The elevator system had been tricky to set up, so I decided to revert to a backup save (Aroma Backup) from about 15 minutes earlier. When I loaded the backup save, I spawned near where the pump had been working and noticed that it was gone, along with the Ender IO pipes and Ender Storage tank it was connected to, and that an area of lava it had pumped out and replaced with stone, directly under where it had been set up, was there again. The older save had not taken me back to before that area had been pumped out, because there was still stone in place of lava that had been pumped out after that section. I went up into my base to check the tank that the pump had been emptying into, and found what I'm guessing was the hunk of stone blocks missing from where the lava had reappeared, somehow teleported up about 40 meters and now replacing most of what had been my smeltery. I didn't think to mine up and check if the pump, pipes, and tank were atop the hunk of stone, where they would have been if things had stayed where they originally were down below. ;\
I've no clue what caused this weirdness, but I thought it'd be best to let you know since it may be Ranged Pumps related. No crash occurred, so there's no crash log, but I'm happy to provide any other logs or info that might help. I'm about to start trying earlier backup saves; I'll report back if I find anything that seems relevant. I'm running MC 1.10.2, Forge 2076, Ranged Pumps 0.3 (and several other mods), and using MultiMC 4.11-713.

**Comment by raoulvdberge** [comment]
Something most likely went wrong while you loaded in the backup.
