### ISSUE TITLE
Version 0.3 causes odd startup crashes

### ISSUE THREAD

**Issue by burdoto** [raoulvdberge/rangedpumps#22]
Modpack: [Resonant Rise 4.3.0.5](https://www.atlauncher.com/pack/ResonantRise) [1.10.2] + 11 custom mods

The pack booted up without any problems, but then I added this mod; rangedpumps to both client and server.
While the server started without any issues; the client started crashing mid-launch. When I remove the mod, it launches perfectly fine again.
Then, if i add the mod again, it launched exactly once and since then it began to crash on load again. This is where we are now.

Console Output: http://kaleidox.de/share/crashlogs/rr4305-rangedpumps-001.txt

Update: I have tried my "workaround" again;
- Launch without rangedpumps (Worked)
- Then, launch with rangedpumps (Crashed again)

**Comment by raoulvdberge** [comment]
Version 0.3 has been running fine without any bug reports since Jun 25, 2017.

This makes me think that this issue is caused by another mod (possibly a coremod)?

**Comment by burdoto** [comment]
The only causing mod that I can think of would be OptiFine; and I tested removing  that; did not help.
If this mod is compatible with other modpacks, it is most likely also compatible with this modpack, as from my experience, this modpack series has a very low incompatibility rate.
However, me and my buddy have both been experiencing very odd behaviour of the overall Modpack (frick >1.7 modding, it's bad imo).

**Comment by burdoto** [comment]
As I seem to be the only one experiencing this, I'm closing this issue. Thanks for your help.
