### ISSUE TITLE
Crash when crafting pump

### ISSUE THREAD

**Issue by shadowfacts** [raoulvdberge/rangedpumps#3]
The game crashes when crafting a Ranged Pump (either in a vanilla crafting table or in a TiCon crafting station).

[Crafting Station crash](https://gist.github.com/shadowfacts/ed33993935db797b5838a50ac651879b)
[Vanilla crash](https://gist.github.com/shadowfacts/5f0ea70a80747840863ca8b19e766a62)

Forge version: 12.18.2.2114
Ranged Pumps version: 0.3

**Comment by raoulvdberge** [comment]
I don't have this issue in my testing environment, I suppose this is a pack specific issue.

(Perhaps changed the recipe in something invalid with an external mod?)
