### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by partyanimal** [raoulvdberge/rangedpumps#4]
when im using ranged pumps i make sure to give it power and a redstone signal wich you can also see on the picture. but it doestn work not in the overworld or in the nether and now when i want to pump water i just magicaly got lava from somewhere https://puu.sh/tt9tv/1bb948b675.jpg

**Comment by RobertLSnead** [comment]
Same issue!  Just not working!!!!

![image](https://cloud.githubusercontent.com/assets/5366796/23098285/179d38da-f618-11e6-89f9-4f1c2ce8145d.png)

**Comment by RobertLSnead** [comment]
I have my config file set to not use rf!

**Comment by raoulvdberge** [comment]
@RobertLSnead 

The pump is scanning the area, it takes a while till it reaches your lava (it scans a rectangular area).

Please read about the mod [on Curse](https://minecraft.curseforge.com/projects/ranged-pumps) *before* coming to the issue tracker.

**Comment by RobertLSnead** [comment]
The description is not very clear!  It should say it scans randomly in the zone, The sentence "It'll pump liquids in a rectangular area 1 block under the pump, the size of this rectangular area can be specified in the config." is very misleading.  I was able to get it to work just fine in the nether, over world is not very friendly unless its a huge pool in the scanning zone.

![image](https://cloud.githubusercontent.com/assets/5366796/23098370/9511ec2e-f619-11e6-987a-35442a236c3f.png)

**Comment by raoulvdberge** [comment]
It *doesn't* scan randomly in the zone! In fact, the description says *exactly* how it scans:

![description](https://raoulvdberge.com/EDMKag)
