### ISSUE TITLE
Question: How do you get fluids out? (1.11.2)

### ISSUE THREAD

**Issue by kragnoth** [raoulvdberge/rangedpumps#8]
I've tried pretty much everything I can think of in 1.11.2 to get fluids back out of this pump, and none of them work.

Is it an issue with 1.11.2, or is there a secret way of doing it? Xnet doesn't even work to get fluids out.  I have tried the top and sides, nadda.

**Comment by kde99** [comment]
It doesn't work with extrautils2 and intergrated dynmics either

**Comment by raoulvdberge** [comment]
I'm able to get the fluids out using Extra Utilities. Are you sure you aren't turning the pipe off with the redstone signal that the pump needs by accident?

**Comment by kde99** [comment]
@raoulvdberge well I tired extra util's fluid node on all sides even on the top and redstone is from a side so as long as the pump itself is not a redstone signal then I don't think that the redstone is the problem.

**Comment by kragnoth** [comment]
It might be from the lever on one side sending it to all sides.  It works with a fluid phantom face from AA, so it might simply be that.  (I can get fluid out with a faucet from Tcon)

**Comment by raoulvdberge** [comment]
If you put the lever on the ranged pump, it will send the redstone signal over to the transfer node causing blockage.

Put it on the block *next* to the pump, not *on* the pump.
