### ISSUE TITLE
Range pump don't work or very low

### ISSUE THREAD

**Issue by cap1o** [raoulvdberge/rangedpumps#9]
Hi, 
It's maybe not an issue properly but i'm playing FTB Beyond on my server, i provide power RF and redstone signal to it.
It's very long to start to work when it works and very slow to pump the lava on the nether.
I provide chunkloader too.
I don't know what's the mistake i have done.
It's working well on solo creative party on my client but not in my server online.

I show you the screenshot i hope you can help me because you're the only mod of pump of the modpack to large quantities of liquid.
When i say it's very slow i mean it take 1h IRL to pump 10 000MB.

here the screenshot : https://www.hostingpics.net/viewer.php?id=36775120170621223933.png

I try to figure out how to fix it but i don't know.
Thank you

**Comment by raoulvdberge** [comment]
Then it's scanning an area where there is no lava.
